# Generated by Django 4.2 on 2024-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("movie_name", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("image", models.URLField()),
            ],
        ),
    ]
